In [9]:
import pandas as pd
info={
    "Name":["A","B","C"],
    "CGPA":[8.9,7.7,6.5],
    "Age":[23,34,45]
}
df=pd.DataFrame(info)
s=pd.Series([1,2,3,4],index=["a","b","c","d"])
print(s.index)
print(df)
print(type(df))

Index(['a', 'b', 'c', 'd'], dtype='object')
  Name  CGPA  Age
0    A   8.9   23
1    B   7.7   34
2    C   6.5   45
<class 'pandas.core.frame.DataFrame'>

In [1]:
import pandas as pd
df=pd.DataFrame([[1,2,3,4],[4,5,6,7]],columns=["a","b","c","d"])
print(df)

   a  b  c  d
0  1  2  3  4
1  4  5  6  7

In [5]:
import numpy as np
import pandas as pd
np_arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
df=pd.DataFrame(np_arr,columns=["A","B","C","D"])
print(df)

   A   B   C   D
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [6]:
import pandas as pd
df=pd.read_csv("emp_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [47]:
import pandas as pd
df=pd.read_csv("global_air.csv")
# print(df.head(3))
# print(df.tail())
# print(df.sample())
# print(df.info())
# print(df.shape)
# print(df.describe())
# print(df.columns)
# print(df.nunique())
# print(df[["city","aqi"]])
# print(df.loc[0:2])
# print(df.loc[0:2,["city","aqi"]])
# print(df.iloc[0:2,[2]])
# print(df.at[0,"city"])
# print(df.iat[0,2])
# print(df[df["aqi"]>100])
#query Method
temp=18.504
df.query("aqi>100 & temperature==@temp")[["city","country"]]

           city country
0      New York      US
13300    Moscow      RU

In [67]:
#Handling Missing Values
import pandas as pd
df=pd.read_csv("Raw_data.csv")
# print(df.isnull())
# print(df.isna().sum())
# df.dropna(axis=1)
clean_data=df.copy()
# df.fillna(100)
clean_data=clean_data.ffill()
# df.bfill()
# print(df)
clean_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [74]:
# handling duplicate values
df.duplicated()
df[["age","gender"]].duplicated
df.drop_duplicates(inplace=True)

In [76]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [88]:
# df.dtypes
# df2=df.copy()
# df2=df2.fillna(0)
# df2["age"]=df2["age"].astype("int64")
# df2.dtype
df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64")

print(df2.dtypes)

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [92]:
df1=("08-07-2026")
import pandas as pd
df1=pd.to_datetime(df1)
print(type(df1))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [97]:
import pandas as pd
df=pd.read_csv("global_air.csv")
df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    errors="coerce"
)
print(df["timestamp"].dtype)

datetime64[ns]

In [12]:
import pandas as pd
df=pd.read_csv("Raw_data.csv")
df2=df.copy()
df2["Tax"]=df2["income"].apply(lambda x:"20%" if x>=50000 else "10%")
df2["category"]=df2["age"].apply(lambda x:"child" if x<20 else "adult")
gender_map={"male":"M","Female":"F","Unknown":"U"}
df2["gender"]=df2["gender"].map(gender_map)
df2=df2.assign(new_age=df2["age"]+1)
df2

    id          name   age country gender   income  Tax category  new_age
0    1      John Doe  29.0     USA    NaN  55000.0  20%    adult     30.0
1    1      John Doe  29.0     USA    NaN  55000.0  20%    adult     30.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%    adult      NaN
3    3          Alex   NaN     USA      U  47000.0  10%    adult      NaN
4    4  Maria Garcia  34.0   Spain      F      NaN  10%    adult     35.0
5    5        Li Wei  27.0   China    NaN  51000.0  20%    adult     28.0
6    6           NaN  45.0   India      F  73000.0  20%    adult     46.0
7    7    Ahmed Khan  38.0     NaN    NaN  68000.0  20%    adult     39.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%    adult     30.0
9    9   Carlos Ruiz   NaN  Mexico    NaN  45000.0  10%    adult      NaN
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%    adult     32.0

In [16]:
import pandas as pd
df=pd.read_csv("Raw_data.csv")
df2=df.copy()
df2["Tax"]=df2["income"].apply(lambda x:"20%" if x>=50000 else "10%")
df2["category"]=df2["age"].apply(lambda x:"child" if x<20 else "adult")
gender_map={"male":"M","Female":"F","Unknown":"U"}
df2["gender"]=df2["gender"].map(gender_map)
df2=df2.assign(new_age=df2["age"]+1)
df2["country"]=df2["country"].replace("USA","US")
df2

    id          name   age country gender   income  Tax category  new_age
0    1      John Doe  29.0      US    NaN  55000.0  20%    adult     30.0
1    1      John Doe  29.0      US    NaN  55000.0  20%    adult     30.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%    adult      NaN
3    3          Alex   NaN      US      U  47000.0  10%    adult      NaN
4    4  Maria Garcia  34.0   Spain      F      NaN  10%    adult     35.0
5    5        Li Wei  27.0   China    NaN  51000.0  20%    adult     28.0
6    6           NaN  45.0   India      F  73000.0  20%    adult     46.0
7    7    Ahmed Khan  38.0     NaN    NaN  68000.0  20%    adult     39.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%    adult     30.0
9    9   Carlos Ruiz   NaN  Mexico    NaN  45000.0  10%    adult      NaN
10  10   Emily Davis  31.0      US    NaN  58000.0  20%    adult     32.0

In [51]:
import pandas as pd
df=pd.read_csv("Raw_data.csv")
df2=df.copy()
# df2.columns=["ID","NAME","AGE","Country","Income","Gender"]
# df2=df2.rename(columns={"Income":"TAX"})
df2=df2.sort_values("income",ascending=False)
df2=df2.sort_index()

# df2=df2.reset_index(drop=True)
df2["Ranking"]=df2["income"].rank()
df2

    id          name   age country   gender   income  Ranking
0    1      John Doe  29.0     USA     Male  55000.0      4.5
1    1      John Doe  29.0     USA     Male  55000.0      4.5
2    2    Jane Smith   NaN  Canada   Female  62000.0      7.5
3    3          Alex   NaN     USA  Unknown  47000.0      2.0
4    4  Maria Garcia  34.0   Spain   Female      NaN      NaN
5    5        Li Wei  27.0   China     Male  51000.0      3.0
6    6           NaN  45.0   India   Female  73000.0     10.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0      9.0
8    8    Rachel Lee  29.0     USA   Female  62000.0      7.5
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0      1.0
10  10   Emily Davis  31.0     USA      NaN  58000.0      6.0

In [62]:
import pandas as pd
df=pd.read_csv("Raw_data.csv")
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()
df["country"].str.contains("india",case=False).sum()
df["name"].str.split(" ")

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [7]:
import pandas as pd
df=pd.read_csv("Raw_data.csv")
df2=df.copy()
d=["name","age","country","gender","income","id"]
# d=[col for col in df2.columns  if col!="id"]+["id"]
df2[d]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [9]:
df2=df.copy()
df2=df2.drop_duplicates()
df2=df2.fillna(0)
df2=df2.sort_values("income")
df2=df2.reset_index(drop=True)
df2.to_csv("sorted_data.csv")

In [23]:
# df.groupby("country")["income"].sum()
df.groupby("country")["income"].agg(["mean","max","min","sum"])
df.groupby("gender")["income"].agg(av_income="mean",max_income="max",min_income="min")
df.groupby("country").agg({
    "income":"max",
    "age":"mean"
})
df.groupby("country").agg(
    max_income=("income","max"),
    avg_age=("age","mean")
)

         max_income  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.5

In [27]:
#melt & pivot


import pandas as pd

df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22]
   
})
df2=df.melt(
    id_vars=["country","year"],
    value_vars=["sales","profit"],
    var_name="metrix",
    value_name="values"

)
df2

  country  year  metrix  values
0     USA  2020   sales     100
1     USA  2021   sales     120
2   India  2020   sales      90
3   India  2021   sales     110
4     USA  2020  profit      20
5     USA  2021  profit      25
6   India  2020  profit      18
7   India  2021  profit      22

In [30]:
pivot_data=df2.pivot(
    index=["country","year"],
    columns="metrix",
    values="values"

)
pivot_data

metrix        profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [35]:
import pandas as pd

df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})
df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})
# print(df_customers)
# print(df_orders)
pd.merge(df_customers,df_orders,on="customer_id") #inner
pd.merge(df_customers,df_orders,on="customer_id",how="left") #left
pd.merge(df_customers,df_orders,on="customer_id",how="right")#right
pd.merge(df_customers,df_orders,on="customer_id",how="outer")#outer

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0